language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x
  - 1.18.x
  - 1.19.x
  - tip
env:
  - GO111MODULE=on GOOS=linux   GOARCH=amd64
  - GO111MODULE=on GOOS=linux   GOARCH=i386
  - GO111MODULE=on GOOS=darwin  GOARCH=amd64
  - GO111MODULE=on GOOS=darwin  GOARCH=i386
  - GO111MODULE=on GOOS=windows GOARCH=amd64
  - GO111MODULE=on GOOS=windows GOARCH=i386
install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
script:
  - golangci-lint run
  # onlytest on linux
  - if [ "$GOOS" = "linux" ]; then go test -race -coverprofile=coverage.txt -covermode=atomic ./...; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
